config/routes.rb
#                                  POST     /users(.:format)                                       users#create
#                         new_user GET      /users/new(.:format)                                   users#new
#                        edit_user GET      /users/:id/edit(.:format)                              users#edit
#                             user GET      /users/:id(.:format)                                   users#show
#                                  PATCH    /users/:id(.:format)                                   users#update
#                                  PUT      /users/:id(.:format)                                   users#update
#                                  DELETE   /users/:id(.:format)                                   users#destroy
#                          courses GET      /courses(/page/:page)(.:format)                        courses#index
#               course_enrollments POST     /courses/:course_id/enrollments(.:format)              enrollments#create
#                                  GET      /courses(.:format)                                     courses#index
#                           course GET      /courses/:id(.:format)                                 courses#show
#                           lesson GET      /lessons/:id(.:format)                                 lessons#show
#       instructor_course_sections POST     /instructor/courses/:course_id/sections(.:format)      instructor/sections#create
#        instructor_course_section PATCH    /instructor/courses/:course_id/sections/:id(.:format)  instructor/sections#update
#                                  PUT      /instructor/courses/:course_id/sections/:id(.:format)  instructor/sections#update
#               instructor_courses POST     /instructor/courses(.:format)                          instructor/courses#create
#            new_instructor_course GET      /instructor/courses/new(.:format)                      instructor/courses#new
#                instructor_course GET      /instructor/courses/:id(.:format)                      instructor/courses#show
#             instructor_dashboard GET      /instructor/dashboard(.:format)                        instructor/courses#index
#       instructor_section_lessons POST     /instructor/sections/:section_id/lessons(.:format)     instructor/lessons#create
#        instructor_section_lesson PATCH    /instructor/sections/:section_id/lessons/:id(.:format) instructor/lessons#update
#                                  PUT      /instructor/sections/:section_id/lessons/:id(.:format) instructor/lessons#update
#                     my_dashboard GET      /my_dashboard(.:format)                                dashboards#show
#                    profile_posts GET      /profile/posts(.:format)                               users#posts
#                          profile GET      /profile/:id(.:format)                                 profiles#show
#                     edit_profile GET      /profile/:id/edit(.:format)                            profiles#edit
#                   update_profile PATCH    /profile/edit(.:format)                                profiles#update
#                       my_profile GET      /my_profile(.:format)                                  profiles#my_profile
#                         profiles GET      /profiles(.:format)                                    profiles#index
#                    enrolled_page GET      /my_enrollements(.:format)                             enrollments#show
#                           skills GET      /skills(.:format)                                      skills#index
#                                  POST     /skills(.:format)                                      skills#create
#                        new_skill GET      /skills/new(.:format)                                  skills#new
#                       edit_skill GET      /skills/:id/edit(.:format)                             skills#edit
#                            skill GET      /skills/:id(.:format)                                  skills#show
#                                  PATCH    /skills/:id(.:format)                                  skills#update
#                                  PUT      /skills/:id(.:format)                                  skills#update
#                                  DELETE   /skills/:id(.:format)                                  skills#destroy
#                         myskills GET      /myskills(.:format)                                    myskills#index
#                                  POST     /myskills(.:format)                                    myskills#create
#                      new_myskill GET      /myskills/new(.:format)                                myskills#new
#                     edit_myskill GET      /myskills/:id/edit(.:format)                           myskills#edit
#                          myskill GET      /myskills/:id(.:format)                                myskills#show
#                                  PATCH    /myskills/:id(.:format)                                myskills#update
#                                  PUT      /myskills/:id(.:format)                                myskills#update
#                                  DELETE   /myskills/:id(.:format)                                myskills#destroy
#                        my_skills GET      /my_skills(.:format)                                   myskills#index
#                         category GET      /category/:id(.:format)                                categories#show
#                            posts GET      /posts(.:format)                                       posts#index
#                                  POST     /posts(.:format)                                       posts#create
#                         new_post GET      /posts/new(.:format)                                   posts#new
#                        edit_post GET      /posts/:id/edit(.:format)                              posts#edit
#                             post GET      /posts/:id(.:format)                                   posts#show
#                                  PATCH    /posts/:id(.:format)                                   posts#update
#                                  PUT      /posts/:id(.:format)                                   posts#update
#                                  DELETE   /posts/:id(.:format)                                   posts#destroy
#                       users_json GET      /users/json(.:format)                                  users#json
#                          publish PUT      /publish(.:format)                                     posts#publish
#                        unpublish PUT      /unpublish(.:format)                                   posts#unpublish
#
# Routes for RailsAdmin::Engine:
#   dashboard GET         /                                      rails_admin/main#dashboard
#       index GET|POST    /:model_name(.:format)                 rails_admin/main#index
#         new GET|POST    /:model_name/new(.:format)             rails_admin/main#new
#      export GET|POST    /:model_name/export(.:format)          rails_admin/main#export
# bulk_delete POST|DELETE /:model_name/bulk_delete(.:format)     rails_admin/main#bulk_delete
# bulk_action POST        /:model_name/bulk_action(.:format)     rails_admin/main#bulk_action
#        show GET         /:model_name/:id(.:format)             rails_admin/main#show
#        edit GET|PUT     /:model_name/:id/edit(.:format)        rails_admin/main#edit
#      delete GET|DELETE  /:model_name/:id/delete(.:format)      rails_admin/main#delete
# show_in_app GET         /:model_name/:id/show_in_app(.:format) rails_admin/main#show_in_app
#

Rails.application.routes.draw do

  #
  # Homepage
  #
  root to: 'homes#show'
  #
  # Rails Admin
  #
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  #
  # Chat
  #
  get 'profiles/chat'
  get 'profiles/profile'
  resources :urls, only: [:show, :new, :create]
  #
  # Devise
  #
  devise_for :admins, controllers: { sessions: 'admin/sessions' }
  devise_for :users, controllers: { sessions: 'users/sessions', :omniauth_callbacks => "users/omniauth_callbacks" }
  #
  #
  # devise_scope :user do
  #   get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
  #   get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  # end
  #
  #
  # Users
  #
  resources :users
  #
  # Courses, Lessons, Instructors
  #
  resources :courses, only: [:index, :show] do
    get "(page/:page)", action: :index, on: :collection, as: ""
    resources :enrollments, only: [:create]
  end

  resources :lessons, only: :show

  namespace :instructor do
  resources :courses, only: [:new, :create, :show] do
    resources :sections, only: [:create, :update]
  end
  get 'dashboard', to: 'courses#index', as: :dashboard
  resources :sections, only: [] do
    resources :lessons, only: [:create, :update]
  end
end


  #
  # Dashboards
  #
  get 'my_dashboard', to: 'dashboards#show', as: :my_dashboard
  #
  # Profiles
  #
  # get 'profile/:user_id/edit', to: 'profiles#edit', as: :profile_path
  get 'profile/posts', to: 'users#posts', as: :profile_posts
  get 'profile/:id', to: 'profiles#show', as: :profile
  get 'profile/:id/edit', to: 'profiles#edit', as: :edit_profile
  patch 'profile/edit', to: 'profiles#update', as: :update_profile
  get 'my_profile', to: 'profiles#my_profile', as: :my_profile
  get 'profiles', to: 'profiles#index', as: :profiles
  #
  # Course Enrollments
  #get "enrolled/:enrolled_page", to: 'enrollments#show', as: "enrolled_page"
  get "my_enrollements", to: 'enrollments#show', as: "enrolled_page"
  #
  #
  # Skills
  #
  resources :skills
  resources :myskills
  #
  get 'my_skills', to: 'myskills#index', as: :my_skills
  #get 'new_skills', to: 'skills#new', as: :new_skills
  #
  # Categories
  #
  get 'category/:id', to: 'categories#show', as: :category
  #
  # Posts
  #
  resources :posts

app/models/myskill.rb
# == Schema Information
#
# Table name: myskills
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  skill_id   :integer
#  score      :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Myskill < ApplicationRecord
  belongs_to :user
  belongs_to :skill

  validates :user_id, presence: true
  validates :skill_id, presence: true
  validates_uniqueness_of :skill_id, scope: :user_id
end

app/controllers/myskills_controller.rb
class MyskillsController < ApplicationController
  before_action :authenticate_user!, :except => [:show, :index]
  before_action :set_myskill, only: [:show, :edit, :update, :destroy]
  before_action :check_current_user_is_owner, only: [:edit, :update, :destroy]

  # GET /myskills
  # GET /myskills.json
  def index
    @myskills =  current_user.myskills.all.order(created_at: :desc).includes(skill: :category)
    check_myskills_empty
  end

  # GET /myskills/1
  # GET /myskills/1.json
  def show
  end

  def myskills
  end
  # GET /myskills/new
  def new
    @myskill = Myskill.new
  end

  # GET /myskills/1/edit
  def edit
  end

  # POST /myskills
  # POST /myskills.json
  def create
    @myskill = Myskill.new(myskill_params)
    @myskill.user_id = current_user.id

    respond_to do |format|
      if @myskill.save
        format.html { redirect_to my_skills_path, notice: 'Myskill was successfully created.' }
        format.json { render :show, status: :created, location: @myskill }
      else
        format.html { render :new }
        format.json { render json: @myskill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /myskills/1
  # PATCH/PUT /myskills/1.json
  def update
    respond_to do |format|
      if @myskill.update(myskill_params)
        format.html { redirect_to @myskill, notice: 'Myskill was successfully updated.' }
        format.json { render :show, status: :ok, location: @myskill }
      else
        format.html { render :edit }
        format.json { render json: @myskill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /myskills/1
  # DELETE /myskills/1.json
  def destroy
    @myskill.destroy
    respond_to do |format|
      format.html { redirect_to myskills_url, notice: 'Myskill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def check_myskills_empty
    @myskillscheck = current_user.skills
    if @myskillscheck.blank?
      redirect_to new_myskill_path, notice: 'Skills are missing from your profile. Please add a new skill.'
    end
  end

  def check_current_user_is_owner
    @myskill = Myskill.find(params[:id])
    unless current_user.id == @myskill.user_id
      redirect_to myskills_url, notice: 'You do not own this skill, please behave.'
    end
  end

    # Use callbacks to share common setup or constraints between actions.
    def set_myskill
      @myskill = Myskill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def myskill_params
      params.require(:myskill).permit(:skill_id, :score)
    end
end

app/helpers/myskills_helper.rb
module MyskillsHelper
end

app/views/myskills/_form.html.erb
<%= form_for(myskill) do |f| %>
  <div class="panel panel-default">
    <% if myskill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(myskill.errors.count, "error") %> prohibited this myskill from being saved:</h2>
      <ul>
        <% myskill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

  <div class="panel-heading">
    <h1><%= controller.action_name.capitalize %> Myskill</h1>
  </div>
  <div class="panel-body">

    <div class="form-group row">
      <%= f.label :skill_id, class: 'col-sm-2 form-control-label'%>
      <%= f.collection_select(:skill_id, Skill.all, :id, :name, {}, {class:'col-sm-1'}) %>
    </div>

    <div class="form-group row">
      <%= f.label :score, class: 'col-sm-2 form-control-label' %>
      <div class="col-sm-6" id='star-rating'></div>
    </div>

    <div class="actions">
      <%= f.submit 'Add as my skill', class: 'btn btn-success' %>
    </div>

  </div>
</div>
<% end %>
<script>
$('#star-rating').raty({
  path: '/assets',
  scoreName: 'myskill[score]'
});
</script>

app/views/myskills/edit.html.erb
<%= render 'shared/navbar' %>
<div class="main-container">
  <div class="container">
    <%= render 'form', myskill: @myskill %>
    <%= link_to 'Show', @myskill %> |
    <%= link_to 'Back', myskills_path %>
  </div>
</div>

<%= render 'shared/footer' %>

app/views/myskills/index.html.erb
<%= render 'shared/navbar' %>
<div class="main-content">
  <div class="container">
    <div class="row">
      <div>
        <%= link_to 'New skill', new_myskill_path, class: 'btn btn-primary btn-lg' %>
      </div>
      <br>
      <table class="table table-striped ta">
        <tr>
          <th colspan="">Score</th>
          <th colspan="">Category</th>
          <th colspan="">Skill</th>
          <th colspan=""></th>
          <th colspan=""></th>
          <th colspan=""></th>
        </tr>
        <% @myskills.each do |mys| %>
        <tr>
          <td class="star-rating" data-score="<%= mys.score %>"></td>
          <td><%= mys.skill.category.name %></td>
          <td><%= mys.skill.name %></td>
          <td></td>
          <td><%= link_to 'Edit', edit_myskill_path(mys), class: 'btn btn-sm btn-warning' %></td>
          <td><%= link_to 'Remove', myskill_path(mys), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %></td>
        </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>
<%= render 'shared/footer' %>
<script>
$('.star-rating').raty({
  path: '/assets/',
  readOnly: true,
  score: function() {
    return $(this).attr('data-score');
  }
});
</script>

app/views/myskills/new.html.erb
<%= render 'shared/navbar' %>

<div class="main-container">
  <div class="container">
    <%= render 'form', myskill: @myskill %>
    <%= link_to 'Back', myskills_path %>
  </div>
</div>

<%= render 'shared/footer' %>

app/views/myskills/show.html.erb
<%= render 'shared/navbar' %>
<p>
  <strong>User:</strong>
  <%= @myskill.user.email %>
  <br>
  <%= @myskill.user.name %>
</p>

<p>
  <strong>Skill:</strong>
  <%= @myskill.skill.name %>
</p>

<p>
  <strong>Score:</strong>
  <%= @myskill.score %>
</p>
<%= link_to 'Edit', edit_myskill_path(@myskill) %> |
<%= link_to 'Back', myskills_path %>